### ISSUE TITLE
the client stuck on loading screen

### ISSUE THREAD

**Issue by Sapphire-code** [Gatohost/gatoclient#13]
Whenever I am opening the client it's stuck on the initializing screen.
here is a screenshot.
![image](https://user-images.githubusercontent.com/85494077/148063866-d9b0ad51-2c1b-4234-ab88-2930d4cfe231.png)

Please fix this soon & no it's not my internet.

**Comment by creepycats** [comment]
So basically krunker hates sky color now. I have something automatically doing that and its causing it to instantly fuck up most people's client. 

Since I lost my old files, I am working on getting what i dont have back. For now, join my discord and use my settings that I posted over your current ones

**Comment by Sapphire-code** [comment]
oof. I don't have discord.
could you maybe post the pastebin link over here?
